#include "dearsql/database.hpp"
#include "dearsql/ddl_utils.hpp"
#include "dearsql/sql_builder.hpp"
#include <format>
#include <functional>
#include <regex>

namespace dearsql {

namespace {

Status toStatus(const QueryResult& r) {
    return r.success() ? Status{true, ""} : Status{false, r.errorMessage()};
}

const StatementResult& firstOrThrow(const QueryResult& r) {
    if (!r.success())
        throw Error(r.errorMessage().empty() ? "query failed" : r.errorMessage());
    return r.statements.front();
}

} // namespace

std::vector<std::vector<std::string>> IDatabase::getTableData(const Table& table, int limit,
                                                              int offset,
                                                              const std::string& whereClause,
                                                              const std::string& orderByClause) {
    auto builder = createSQLBuilder(type());
    auto r = execute(builder->selectAll(table, whereClause, orderByClause, limit, offset), 0);
    return firstOrThrow(r).tableData;
}

std::vector<std::string> IDatabase::getColumnNames(const Table& table) {
    auto r = execute(createSQLBuilder(type())->columnNames(table), 0);
    std::vector<std::string> names;
    for (const auto& row : firstOrThrow(r).tableData) {
        if (!row.empty())
            names.push_back(row[0]);
    }
    return names;
}

int IDatabase::getRowCount(const Table& table, const std::string& whereClause) {
    auto r = execute(createSQLBuilder(type())->countRows(table, whereClause), 1);
    const auto& rows = firstOrThrow(r).tableData;
    if (rows.empty() || rows[0].empty())
        return 0;
    try {
        return std::stoi(rows[0][0]);
    } catch (...) {
        return 0;
    }
}

namespace {

std::string lit(const std::string& s) {
    return "'" + ddl_utils::escapeSingleQuotes(s) + "'";
}

std::string joined(const std::vector<std::vector<std::string>>& rows, size_t col,
                   const std::string& sep) {
    std::string out;
    for (const auto& r : rows) {
        if (r.size() <= col || isNullSentinel(r[col]))
            continue;
        const auto first = r[col].find_first_not_of(" \t\r\n");
        if (first == std::string::npos)
            continue;
        const auto last = r[col].find_last_not_of(" \t\r\n");
        out += (out.empty() ? "" : sep) + r[col].substr(first, last - first + 1);
    }
    return out;
}

// catalog-built: postgres has no CREATE TABLE function. covers identity, generated
// and serial columns, every constraint as pg_get_constraintdef prints it, indexes not
// backing a constraint, partition keys, UNLOGGED and comments
std::string postgresTableDdl(
    const std::string& qualified,
    const std::function<std::vector<std::vector<std::string>>(const std::string&)>& rows) {
    const std::string rel = lit(qualified) + "::regclass";
    auto head = rows(std::format(
        "SELECT quote_ident(n.nspname) || '.' || quote_ident(c.relname), c.relpersistence, "
        "COALESCE(pg_get_partkeydef(c.oid), ''), COALESCE(obj_description(c.oid, "
        "'pg_class'), '') "
        "FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.oid = {}",
        rel));
    if (head.empty() || head[0].size() < 4)
        throw Error("table not found: " + qualified);
    const std::string name = head[0][0];

    std::vector<std::string> lines;
    std::vector<std::string> comments;
    static const std::regex serialDefault(R"(^nextval\('[^']+'::regclass\)$)");
    for (const auto& c :
         rows(std::format("SELECT quote_ident(a.attname), format_type(a.atttypid, a.atttypmod), "
                          "a.attnotnull::text, COALESCE(pg_get_expr(d.adbin, d.adrelid), ''), "
                          "COALESCE(to_jsonb(a)->>'attidentity', ''), "
                          "COALESCE(to_jsonb(a)->>'attgenerated', ''), "
                          "COALESCE(col_description(a.attrelid, a.attnum), '') "
                          "FROM pg_attribute a LEFT JOIN pg_attrdef d "
                          "  ON d.adrelid = a.attrelid AND d.adnum = a.attnum "
                          "WHERE a.attrelid = {} AND a.attnum > 0 AND NOT a.attisdropped "
                          "ORDER BY a.attnum",
                          rel))) {
        if (c.size() < 7)
            continue;
        std::string type = c[1];
        std::string extra;
        if (c[5] == "s" || c[5] == "v") {
            extra = std::format(" GENERATED ALWAYS AS ({}) {}", c[3],
                                c[5] == "s" ? "STORED" : "VIRTUAL");
        } else if (c[4] == "a" || c[4] == "d") {
            extra =
                c[4] == "a" ? " GENERATED ALWAYS AS IDENTITY" : " GENERATED BY DEFAULT AS IDENTITY";
        } else if (std::regex_match(c[3], serialDefault) &&
                   (type == "integer" || type == "bigint" || type == "smallint")) {
            // the sequence comes with the column instead of a dangling nextval()
            type = type == "integer" ? "serial" : type == "bigint" ? "bigserial" : "smallserial";
        } else if (!c[3].empty()) {
            extra = " DEFAULT " + c[3];
        }
        lines.push_back(
            std::format("{} {}{}{}", c[0], type, extra, c[2] == "true" ? " NOT NULL" : ""));
        if (!c[6].empty())
            comments.push_back(
                std::format("COMMENT ON COLUMN {}.{} IS {};", name, c[0], lit(c[6])));
    }
    for (const auto& c :
         rows(std::format("SELECT quote_ident(conname), pg_get_constraintdef(oid, true) FROM "
                          "pg_constraint "
                          "WHERE conrelid = {} AND contype IN ('p', 'u', 'c', 'x', 'f') "
                          "ORDER BY CASE contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'c' THEN 2 "
                          "WHEN 'x' THEN 3 ELSE 4 END, conname",
                          rel))) {
        if (c.size() >= 2)
            lines.push_back(std::format("CONSTRAINT {} {}", c[0], c[1]));
    }

    std::string sql =
        std::format("CREATE {}TABLE {} (\n", head[0][1] == "u" ? "UNLOGGED " : "", name);
    for (size_t i = 0; i < lines.size(); ++i)
        sql += "    " + lines[i] + (i + 1 < lines.size() ? ",\n" : "\n");
    sql += ")";
    if (!head[0][2].empty())
        sql += " PARTITION BY " + head[0][2];
    sql += ";";

    const auto indexes = joined(
        rows(std::format("SELECT pg_get_indexdef(i.indexrelid) || ';' FROM pg_index i "
                         "WHERE i.indrelid = {} AND NOT EXISTS (SELECT 1 FROM pg_constraint c "
                         "  WHERE c.conindid = i.indexrelid AND c.conrelid = i.indrelid) "
                         "ORDER BY 1",
                         rel)),
        0, "\n");
    if (!indexes.empty())
        sql += "\n" + indexes;
    if (!head[0][3].empty())
        sql += std::format("\nCOMMENT ON TABLE {} IS {};", name, lit(head[0][3]));
    for (const auto& c : comments)
        sql += "\n" + c;
    return sql;
}

} // namespace

std::string IDatabase::tableDdl(const std::string& tableName) {
    auto builder = createSQLBuilder(type());
    const std::string schema = schemaName();
    const std::string qualified = schema.empty() ? builder->quoteIdentifier(tableName)
                                                 : builder->quoteIdentifier(schema) + "." +
                                                       builder->quoteIdentifier(tableName);
    const auto rows = [&](const std::string& sql) {
        return firstOrThrow(execute(sql, 0)).tableData;
    };
    const auto nonEmpty = [&](std::string ddl) {
        if (ddl.empty())
            throw Error("table not found: " + tableName);
        return ddl;
    };

    switch (type()) {
    case DatabaseType::POSTGRESQL:
        return postgresTableDdl(qualified, rows);
    case DatabaseType::REDSHIFT:
        return nonEmpty(joined(rows("SHOW TABLE " + qualified), 0, "\n"));
    case DatabaseType::MYSQL:
    case DatabaseType::MARIADB:
        return nonEmpty(joined(rows("SHOW CREATE TABLE " + qualified), 1, "")) + ";";
    case DatabaseType::SQLITE:
        // the table first, then its explicit indexes (autoindexes have no sql)
        return nonEmpty(joined(rows(std::format("SELECT sql || ';' FROM sqlite_master "
                                                "WHERE tbl_name = {} AND sql IS NOT NULL "
                                                "AND type IN ('table', 'index') "
                                                "ORDER BY type = 'index', name",
                                                lit(tableName))),
                               0, "\n"));
    case DatabaseType::DUCKDB: {
        const std::string where =
            std::format("database_name = current_database() AND schema_name = {} AND "
                        "table_name = {}",
                        schema.empty() ? "current_schema()" : lit(schema), lit(tableName));
        auto ddl = nonEmpty(joined(rows("SELECT sql FROM duckdb_tables() WHERE " + where), 0, ""));
        const auto indexes = joined(
            rows("SELECT sql FROM duckdb_indexes() WHERE sql IS NOT NULL AND " + where), 0, "\n");
        return indexes.empty() ? ddl : ddl + "\n" + indexes;
    }
    case DatabaseType::ORACLE: {
        // no storage/tablespace noise, statements terminated
        execute("BEGIN "
                "DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, "
                "'SEGMENT_ATTRIBUTES', FALSE); "
                "DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, "
                "'SQLTERMINATOR', TRUE); END;",
                0);
        const std::string owner = schema.empty() ? "USER" : lit(schema);
        auto ddl = nonEmpty(
            joined(rows(std::format("SELECT DBMS_METADATA.GET_DDL('TABLE', {}, {}) FROM dual",
                                    lit(tableName), owner)),
                   0, ""));
        const auto indexes = joined(
            rows(std::format("SELECT DBMS_METADATA.GET_DDL('INDEX', i.index_name, i.owner) "
                             "FROM all_indexes i WHERE i.table_name = {} AND i.table_owner = {} "
                             "AND i.index_type <> 'LOB' AND NOT EXISTS (SELECT 1 FROM "
                             "all_constraints c WHERE c.owner = i.table_owner "
                             "AND c.index_name = i.index_name) ORDER BY i.index_name",
                             lit(tableName), owner)),
            0, "\n");
        return indexes.empty() ? ddl : ddl + "\n" + indexes;
    }
    case DatabaseType::MONGODB:
    case DatabaseType::REDIS:
        throw Error("no table DDL for this database type");
    default:
        break;
    }
    auto table = describeTable(tableName);
    if (table.columns.empty())
        throw Error("table not found: " + tableName);
    return builder->tableDdl(table, schema);
}

Status IDatabase::createTable(const Table& table) {
    auto builder = createSQLBuilder(type());
    const std::string schema = table.schema.empty() ? schemaName() : table.schema;
    return toStatus(execute(builder->createTable(table, schema), 0));
}

Status IDatabase::renameTable(const std::string& oldName, const std::string& newName) {
    return toStatus(execute(createSQLBuilder(type())->renameTable(schemaName(), oldName, newName), 0));
}

Status IDatabase::dropTable(const std::string& tableName) {
    return toStatus(execute(createSQLBuilder(type())->dropTable(schemaName(), tableName), 0));
}

Status IDatabase::truncateTable(const std::string& tableName) {
    return toStatus(execute(createSQLBuilder(type())->truncateTable(schemaName(), tableName), 0));
}

Status IDatabase::dropColumn(const std::string& tableName, const std::string& columnName) {
    auto builder = createSQLBuilder(type());
    Table t;
    t.name = tableName;
    t.schema = schemaName();
    return toStatus(execute(builder->dropColumn(builder->qualifiedName(t), columnName), 0));
}

Status IDatabase::dropView(const std::string& viewName, bool isMaterialized) {
    auto builder = createSQLBuilder(type());
    Table t;
    t.name = viewName;
    t.schema = schemaName();
    return toStatus(execute(std::string(isMaterialized ? "DROP MATERIALIZED VIEW " : "DROP VIEW ") +
                                builder->qualifiedName(t),
                            0));
}

} // namespace dearsql
